# Generated by Django 4.1.2 on 2022-12-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missingpersonsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age_at_missing',
            field=models.CharField(default=10, max_length=3),
        ),
    ]
